"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MolDesigner.py']
DATA_FILES = [('images', ['images/back.png','images/forward.png','images/next.png','images/pause.png','images/play.png','images/previous.png'])]
OPTIONS = {
	'argv_emulation': True,
	'optimize': 2,
	'iconfile':'images/icon.icns',
	'includes': ['wx', 'OpenGL.GL', 'OpenGL.GLU', 'OpenGL.GLUT', 'numpy', 'PIL']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
